<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

namespace Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>data.TaskProgress</code>
 */
class TaskProgress extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .data.TaskProgress.Record records = 8;</code>
     */
    private $records;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Data\TaskProgress\Record[]|\Google\Protobuf\Internal\RepeatedField $records
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .data.TaskProgress.Record records = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>repeated .data.TaskProgress.Record records = 8;</code>
     * @param \Data\TaskProgress\Record[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRecords($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Data\TaskProgress\Record::class);
        $this->records = $arr;

        return $this;
    }

}

