<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

namespace Data;

if (false) {
    /**
     * This class is deprecated. Use Data\TaskProgress\Record instead.
     * @deprecated
     */
    class TaskProgress_Record {}
}
class_exists(TaskProgress\Record::class);
@trigger_error('Data\TaskProgress_Record is deprecated and will be removed in the next major release. Use Data\TaskProgress\Record instead', E_USER_DEPRECATED);

