<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

namespace Data\TaskProgress;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>data.TaskProgress.Record</code>
 */
class Record extends \Google\Protobuf\Internal\Message
{
    /**
     * 资源标签
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    private $tag = '';
    /**
     * 资源链接
     *
     * Generated from protobuf field <code>string url = 2;</code>
     */
    private $url = '';
    /**
     * 资源存储目录
     *
     * Generated from protobuf field <code>string saveDir = 3;</code>
     */
    private $saveDir = '';
    /**
     * 资源存储名
     *
     * Generated from protobuf field <code>string saveName = 4;</code>
     */
    private $saveName = '';
    /**
     * 资源下载起始定位
     *
     * Generated from protobuf field <code>int64 cursor = 5;</code>
     */
    private $cursor = 0;
    /**
     * 当前任务的状态
     *
     * Generated from protobuf field <code>int32 flag = 6;</code>
     */
    private $flag = 0;
    /**
     * 资源体积
     *
     * Generated from protobuf field <code>int64 size = 7;</code>
     */
    private $size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *           资源标签
     *     @type string $url
     *           资源链接
     *     @type string $saveDir
     *           资源存储目录
     *     @type string $saveName
     *           资源存储名
     *     @type int|string $cursor
     *           资源下载起始定位
     *     @type int $flag
     *           当前任务的状态
     *     @type int|string $size
     *           资源体积
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Data::initOnce();
        parent::__construct($data);
    }

    /**
     * 资源标签
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * 资源标签
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * 资源链接
     *
     * Generated from protobuf field <code>string url = 2;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * 资源链接
     *
     * Generated from protobuf field <code>string url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * 资源存储目录
     *
     * Generated from protobuf field <code>string saveDir = 3;</code>
     * @return string
     */
    public function getSaveDir()
    {
        return $this->saveDir;
    }

    /**
     * 资源存储目录
     *
     * Generated from protobuf field <code>string saveDir = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSaveDir($var)
    {
        GPBUtil::checkString($var, True);
        $this->saveDir = $var;

        return $this;
    }

    /**
     * 资源存储名
     *
     * Generated from protobuf field <code>string saveName = 4;</code>
     * @return string
     */
    public function getSaveName()
    {
        return $this->saveName;
    }

    /**
     * 资源存储名
     *
     * Generated from protobuf field <code>string saveName = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSaveName($var)
    {
        GPBUtil::checkString($var, True);
        $this->saveName = $var;

        return $this;
    }

    /**
     * 资源下载起始定位
     *
     * Generated from protobuf field <code>int64 cursor = 5;</code>
     * @return int|string
     */
    public function getCursor()
    {
        return $this->cursor;
    }

    /**
     * 资源下载起始定位
     *
     * Generated from protobuf field <code>int64 cursor = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCursor($var)
    {
        GPBUtil::checkInt64($var);
        $this->cursor = $var;

        return $this;
    }

    /**
     * 当前任务的状态
     *
     * Generated from protobuf field <code>int32 flag = 6;</code>
     * @return int
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * 当前任务的状态
     *
     * Generated from protobuf field <code>int32 flag = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkInt32($var);
        $this->flag = $var;

        return $this;
    }

    /**
     * 资源体积
     *
     * Generated from protobuf field <code>int64 size = 7;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * 资源体积
     *
     * Generated from protobuf field <code>int64 size = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Record::class, \Data\TaskProgress_Record::class);

