<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto

namespace GPBMetadata;

class Data
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca010a0a646174612e70726f746f12046461746122ad010a0c5461736b" .
            "50726f6772657373122a0a077265636f72647318082003280b32192e6461" .
            "74612e5461736b50726f67726573732e5265636f72641a710a065265636f" .
            "7264120b0a03746167180120012809120b0a0375726c180220012809120f" .
            "0a077361766544697218032001280912100a08736176654e616d65180420" .
            "012809120e0a06637572736f72180520012803120c0a04666c6167180620" .
            "012805120c0a0473697a65180720012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

